FROM public.ecr.aws/lambda/python:3.13

# Install your dependencies
COPY requirements.txt ./
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy your function code
COPY lambda_function.py ./

# Set the CMD to your function's handler
CMD ["lambda_function.lambda_handler"]